### ISSUE TITLE
[iOS] feat: 온보딩 스크린 구현

### ISSUE THREAD

**Issue by snnzzoo** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#21]
## ✏️ Summary

Mondee 앱 스토리를 웹툰형식 온보딩 페이지로 알려줍니다.

<br>

## ✨ Description

화면을 아래로 scroll 합니다.

앱을 처음 실행할 때만 보이게 합니다.

시작하기 버튼을 누르면 온보딩 뷰가 사라집니다. (시작하기 버튼은 스크롤을 가장 아래로 내리면 있습니다.)

<br>

## ✓ Todo

- [ ] 화면 Scroll 기능
- [ ] 버튼을 통해 홈 화면으로 이동 
- [ ] 첫 앱 실행시만 보이는 기능
<br>

## 📅 Due Date

- 7월 19일 (월) 23:59까지 완료해주세요. (예시입니다)

<br>

## 🗒️ Note (optional)

<br>
