### ISSUE TITLE
[watchOS] feat: 게임 옵션 스크린 동작

### ISSUE THREAD

**Issue by hyunjuntyler** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#24]
## ✏️ Summary

게임 옵션화면 완료, 일시 정지, 포기 기능을 구현합니다.

<br>

## ✨ Description

<br>

## ✓ Todo
- [ ] 게임 완료 기능 구현
- [ ] 게임 일시정지 기능 구현
- [ ] 게임 포기 기능 구현

<br>
