### ISSUE TITLE
[watchOS] feat: 사용자 움직임 관련 동작 기능 추가

### ISSUE THREAD

**Issue by bulmang** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#25]
## ✏️ Summary

게임중에서 사용자의 움직임에 따라 달라지는 화면을 추가합니다.
### 사용자 움직이고 있을때 
- 캐릭터 샤워하고 있을때 후광효과
- 기쁜 먼디 캐릭터 효과
- 하트가 하나 사라져서 색이 진해졌을때 5초동안 움직임을 유지 했다면 캐릭터는 깨끗한 상태로 변합니다.
### 사용자가 움직이지 않을 때 캐릭터의 동작
- 5초동안 움직이지 않으면,15초간 노랑색 배경이 뜨고 후광도 없어지고 캐릭터가 슬픈 표정이 됩니다.
- 5초동안 타이머가 나오고 화면이 검정 빨강으로 깜빡 거리고 진동이 나옵니다.

## ✨ Description

<br>

## ✓ Todo
- [x] 움직일 때 후광효과, 기쁜 먼디 캐릭터
- [x] 색이 검을때 5초동안 움직임을 유지하면 원래 색으로 변경
- [x] 5초동안 움직이지 않으면 15초간 노랑색 배경,후광효과 제거, 슬픈 먼디 캐릭터
- [x] 20초간 움직이지 않으면 5초동안 타이머가 나오며 화면이 빨강색으로 깜빡거리고 진동

<br>
