### ISSUE TITLE
[watchOS] feat: 게임 성공, 실패 시 기능

### ISSUE THREAD

**Issue by hyunjuntyler** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#26]
## ✏️ Summary

게임 성공, 실패와 관련된 기능

<br>

## ✨ Description

- 게임 성공 시 
  - 성공 페이지에는 물음표 축하 문구가 나옵니다.(이때 진동이 울립니다.)
  - 게임 성공후 워치를 다시 들어와도 게임성공페이지만 나옵니다.
- 게임 실패 시
  - 실패 페이지에는 좌절하는 캐릭터와 다시하기, 포기하기 버튼이 표시됩니다. 사용자는 다시하기 버튼을 선택하여 게임을 새로 시작할 수 있습니다.
  - 포기하기 버튼을 선택하면 정말 포기하시겠습니까? 화면이 나오며 예를 누르면 버튼이 사라지고 캐릭터의 이미지와 "오늘 실패"라는 문구가 표시됩니다.(이때 앱을 나갔다와도 그대로 오늘 실패 문구가 표시됩니다.)
- 게임 종료 후 다음날
  - 게임 종료 (성공, 실패 여부 상관없이) 다음날 다시 게임을 시작하기 전 뷰로 돌아갑니다.

<br>

## ✓ Todo
- [x] 게임 성공시 하루동안 성공 페이지 보여주기
- [x] 게임 실패 시 하루동안 실패 페이지 보여주기
- [x] 게임 다음날 리셋 기능

<br>
