### ISSUE TITLE
[watchOS] feat: 게임 시작 기능

### ISSUE THREAD

**Issue by shine-jung** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#3]
## ✏️ Summary
크라운 휠을 돌려서 게임을 시작합니다.

<br>

## ✨ Description
좌측상단(위치는 HI-Fi에서 결정)에는 먼디로고
상단 섹션에는 캐릭터가 위치하고 하단에는 욕조가 위치합니다.
Digital Crown 좌측에는 화살표 에니메이션이 있습니다.
Digital Crown을 돌리면 캐릭터가 내리가면서 욕조에 들어가면 게임이 시작됩니다.

<br>

## ✓ Todo
- [x] 캐릭터 움직임을 Digital Crown Scroll과 연동
- [x] 화살표 에니메이션 구현
- [x] 캐릭터가 욕조에 들어가면 게임안내페이지 이동
- [x] 게임안내페이지에서 취소버튼을 누르면 먼디 위치 제자리

<br>

## 🗒️ Note (optional)
1. 토요일 밤 12시까지 작업해주세요.
2. Mondee Watch App/View 폴더에 StartScreen.swift 파일을 만들고 거기서 작업해주시면 됩니다.
3. 캐릭터, 욕조과 같은 이미지는 비슷한 사이즈의 목업 파일을 활용해주세요.
4. 시작 동작 로직은 다음 feature에서 작업할 예정입니다. 다음과 같이 TODO 주석으로 작성해주세요.
```
function gameStartHandler () {
  // TODO:: 게임 시작
}
```
