### ISSUE TITLE
[iOS] feat: 청소 등급 기능 구현

### ISSUE THREAD

**Issue by shine-jung** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#46]
## ✏️ Summary

등급 기능을 구현합니다.

<br>

## ✨ Description

- 등급 표시, 다음 등급으로 가는 `Progress bar`와, `questionmark.circle` 버튼을 구현합니다.
  - "안녕하세요 등급님 \n \ 다음등급로 거듭나기까지"
    progress bar가 밑에 위치합니다.
    questionmark.circle 버튼을 누르면 팝업창이나옵니다.
    팝업창은 등급 기준이 나옵니다.
  - 등급 박스를 탭하면 등급 기준이 팝업됩니다.
- 등급을 나누는 기준은 다음과 같습니다.

```
→ 등급을 나누는 기준은?
◦ 청소 성공 횟수
  청응애 : 0~3번
  청린이 : 4~7번
  청년 : 8~11번
  청른이 : 12~15번
  청고수 : 16 이상
→ 레벨 마다 3번 성공하면 다음 등급으로 넘어갑니다.
```

- 추가 사항
  - 등급 마다 홈 View에 먼디가 바뀝니다!
    Watch에서도 먼디가 바뀝니다!

<br>

## ✓ Todo

- [x] 등급 표시 `Text` 구현
- [x] 다음 등급으로 가는 `Progress bar` 구현
- [ ] 팝업으로 이어지는 `questionmark.circle` 버튼 구현

<br>

## 📅 Due Date

- 7월 25일 (화) 23:59까지 완료해주세요.

<br>

## 🗒️ Note (optional)

- 등급 기준은 수정될 수 있습니다.
- 데이터 모델에서 청소 성공 횟수를 불러와야합니다.

<br>
