### ISSUE TITLE
[watchOS] feat: 청소 중 사용자가 움직였을 때 동작

### ISSUE THREAD

**Issue by shine-jung** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#5]
## ✏️ Summary
사용자가 움직이고 있을 때 샤워 호스와 캐릭터의 동작을 구현합니다.

<br>

## ✨ Description
사용자의 움직임을 감지합니다. 사용자가 움직이고 있을 때는 욕조에서 거품이 나오며, 초기 캐릭터의 상태는 깨끗합니다.
사용자가 움직이면서 캐릭터에서 거품효과가 나옵니다.
움직이지 않으면 거품효과가 사라집니다.
거품효과(캐릭터 아래 거품, 움직이는 거품x2, 비누모자,후광)
<br>

## ✓ Todo
- [x] CoreMotion setting 및 받아올 CoreMotion Data 선정
- [x] 받아온 CoreMotion Data 로 어떻게 유저의 움직임을 판단할건지
- [x] 청소, 정지 동작 판별 함수, 클래스로 정리

<br>

## 🗒️ Note (optional)
1. UI는 비슷한 사이즈의 목업 파일을 활용해주세요. (사이즈는 #3 에서 공유받기)
2. 금요일 밤 12시까지 작업해주세요.
