### ISSUE TITLE
[iOS] feat: 캘린더 뷰 대시보드 구현

### ISSUE THREAD

**Issue by shine-jung** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#55]
## ✏️ Summary

캘린터 뷰 하단에 대시보드 구현합니다. 다음 3가지 내용을 표시합니다.

- 이번달 성공 횟수
- 도전 대비 성공률
- 총 성공 횟수

<br>

## ✨ Description

- 달마다 변경되어야 합니다.
  - 이번달 성공률 (이번 달 성공횟수/이번달1일부터 현재날짜)
  - 예시: 오늘이 7월 13 (이번달 성공횟수/13), 7/27 (이번달 성공횟수/27)
  - 도전 대비 성공률 (총 게임성공횟수/총 게임도전수)
  - 총 성공 횟수 (지금까지 성공한 횟수)

<br>

## ✓ Todo

- [x] 이번달 도전 횟수 표시
- [x] 이번달 성공 횟수 표시
- [x] 총 플레이 시간 표시

<br>

## 📅 Due Date

- 7월 19일 (월) 23:59까지 완료해주세요. (예시입니다)

<br>

## 🗒️ Note (optional)

<br>
