### ISSUE TITLE
[iOS] feat: 멸균실 스크린 구현

### ISSUE THREAD

**Issue by shine-jung** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#56]
## ✏️ Summary

멸균실 스크린의 전반적인 내용을 구현합니다.

<br>

## ✨ Description

- 네비게이션 타이틀
  - 아래로 스크롤시 툴바에 타이틀 표시됩니다.
    - 멸균실 타이틀이 크게 보이다가 스크롤 시 화면 위에 보이게 됩니다.
- 멸균실 뷰 설명
  - 멸균실 탭뷰 설명을 표시합니다.
    - 예시: 나의 멸균실에 온걸 환영해 (청소라이팅팀 담당)
- GridView
  - 잠금 해제되거나 잠금된 캐릭터를 표시합니다.
    - 아직 얻지 못한 캐릭터는 잠금 아이콘으로 표시됩니다.
    - 획득한 캐릭터는 캐릭터 이미지가 표시됩니다.(홈에서 확인버튼을 누르고 오면 바뀌어있음)
- 상세 캐릭터 카드
  - 캐릭터 카드 클릭시 상세 카드뷰가 표시됩니다.
    - 캐릭터의 이름, 첫 획득 날짜, 특징, 무게 등 캐릭터의 디테일 정보가 표시됩니다.

<br>

## ✓ Todo

- [x] 네비게이션 타이틀 구현
- [x] 멸균실 뷰 설명 구현
- [x] GridView 구현
- [x] 상세 캐릭터 카드 구현

<br>

## 📅 Due Date

- 7월 19일 (월) 23:59까지 완료해주세요. (예시입니다)

<br>

## 🗒️ Note (optional)

<br>
