### ISSUE TITLE
[watchOS] design: 디자인 시스템 만들기

### ISSUE THREAD

**Issue by hyunjuntyler** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#63]
## ✏️ Summary

앱 전체적인 디자인 시스템 제작

<br>

## ✨ Description

<br>

## ✓ Todo
- [ ] 색상 디자인 시스템
- [ ] 폰트 디자인 시스템
- [ ] 버튼 디자인 시스템

<br>
