### ISSUE TITLE
[watchOS] feat: 추가된 게임 데이터 보내기

### ISSUE THREAD

**Issue by bulmang** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#65]
## ✏️ Summary

기획에서 추가된 데이터들을 보냅니다.
<br>

## ✨ Description

게임 도중 움직임이 없을 때 하트 없어질때마다 iOS에 하트가 없어졌다고 데이터를 보냅니다.
watch에서 측정한 총 움직임 거리를 iOS에 데이터를 보냅니다.
청소 도중 제일 큰 움직임을 측정해서OS에 데이터를 보냅니다.
<br>

## ✓ Todo
- [ ] 제일 큰 움직임 측정후 데이터 보내기 (실패)
- [ ] 총 움직임 거리 (실패)
- [x] 하트 없어질때마다 데이터 보내기 

<br>
