### ISSUE TITLE
[watchOS] data: 실시간 데이터 전송 기능 구현

### ISSUE THREAD

**Issue by bulmang** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#83]
## ✏️ Summary

게임 중 실시간으로 데이터 전송 기능 구현
<br>

## ✨ Description

모델 | 변수 이름 | 타입 | 변수명 | 사용하는 곳
-- | -- | -- | -- | --
모델 제작 필요 | 게임 시작 | Bool | gameStart | 홈,라이브 액티비티
  | 게임 정지 | Bool | gamePause | 라이브 액티비티
  | 남은 하트 | Int | remainingHeartCount | 라이브 액티비티

<br>

## ✓ Todo
- [x] 게임 시작할 때 데이터 전송
- [x] 게임 정지할 때 데이터 전송
- [x] 하트가 하나 사라지면 데이터 전송

<br>
