### ISSUE TITLE
[watchOS] feat: 게임 성공시 동작 구현

### ISSUE THREAD

**Issue by shine-jung** [DeveloperAcademy-POSTECH/MC3-Team5-Mondee#9]
## ✏️ Summary
게임 결과 데이터 전송 및 저장, 성공 스크린으로 이동

<br>

## ✨ Description
게임 결과 데이터 (하트 개수, 움직임 횟수, 타임스탬프 등)을 iOS에 전송하고 성공 스크린으로 이동합니다.

<br>

## ✓ Todo
- [x] 전송할 변수 선정
- [x] 전송할 변수 네이밍 결정
- [x] 전송하는 로직 구현

<br>

## 🗒️ Note (optional)
1. 일요일 밤 12시까지 작업해주세요.
